/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MechanicRouteImport } from './routes/mechanic'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MechanicIndexRouteImport } from './routes/mechanic.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as MechanicWorkOrdersRouteImport } from './routes/mechanic.work-orders'
import { Route as MechanicPurchaseRequestsRouteImport } from './routes/mechanic.purchase-requests'
import { Route as MechanicMaintenanceRouteImport } from './routes/mechanic.maintenance'
import { Route as MechanicInventoryRouteImport } from './routes/mechanic.inventory'
import { Route as DriverWorkOrderRouteImport } from './routes/driver.work-order'
import { Route as DriverToolChecklistRouteImport } from './routes/driver.tool-checklist'
import { Route as DriverTicketsRouteImport } from './routes/driver.tickets'
import { Route as DriverStartOfDayRouteImport } from './routes/driver.start-of-day'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverJobsRouteImport } from './routes/driver.jobs'
import { Route as DriverJobLogRouteImport } from './routes/driver.job-log'
import { Route as DriverInspectionRouteImport } from './routes/driver.inspection'
import { Route as DriverFormsRouteImport } from './routes/driver.forms'
import { Route as DriverEndOfDayRouteImport } from './routes/driver.end-of-day'
import { Route as DebugErrorBoundaryTriggerRouteImport } from './routes/debug.error-boundary-trigger'
import { Route as AdminWorkOrdersRouteImport } from './routes/admin.work-orders'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminTendersRouteImport } from './routes/admin.tenders'
import { Route as AdminSmsLogRouteImport } from './routes/admin.sms-log'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPurchaseRequestsRouteImport } from './routes/admin.purchase-requests'
import { Route as AdminPrepaidTicketsRouteImport } from './routes/admin.prepaid-tickets'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminVehiclesIndexRouteImport } from './routes/admin.vehicles.index'
import { Route as AdminVehiclesIdRouteImport } from './routes/admin.vehicles.$id'
import { Route as AdminInvoicesWorkOrderIdRouteImport } from './routes/admin.invoices.$workOrderId'

const MechanicRoute = MechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicIndexRoute = MechanicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MechanicRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicWorkOrdersRoute = MechanicWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicPurchaseRequestsRoute =
  MechanicPurchaseRequestsRouteImport.update({
    id: '/purchase-requests',
    path: '/purchase-requests',
    getParentRoute: () => MechanicRoute,
  } as any)
const MechanicMaintenanceRoute = MechanicMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicInventoryRoute = MechanicInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MechanicRoute,
} as any)
const DriverWorkOrderRoute = DriverWorkOrderRouteImport.update({
  id: '/work-order',
  path: '/work-order',
  getParentRoute: () => DriverRoute,
} as any)
const DriverToolChecklistRoute = DriverToolChecklistRouteImport.update({
  id: '/tool-checklist',
  path: '/tool-checklist',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTicketsRoute = DriverTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DriverRoute,
} as any)
const DriverStartOfDayRoute = DriverStartOfDayRouteImport.update({
  id: '/start-of-day',
  path: '/start-of-day',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverJobsRoute = DriverJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DriverRoute,
} as any)
const DriverJobLogRoute = DriverJobLogRouteImport.update({
  id: '/job-log',
  path: '/job-log',
  getParentRoute: () => DriverRoute,
} as any)
const DriverInspectionRoute = DriverInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => DriverRoute,
} as any)
const DriverFormsRoute = DriverFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEndOfDayRoute = DriverEndOfDayRouteImport.update({
  id: '/end-of-day',
  path: '/end-of-day',
  getParentRoute: () => DriverRoute,
} as any)
const DebugErrorBoundaryTriggerRoute =
  DebugErrorBoundaryTriggerRouteImport.update({
    id: '/debug/error-boundary-trigger',
    path: '/debug/error-boundary-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWorkOrdersRoute = AdminWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTendersRoute = AdminTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsLogRoute = AdminSmsLogRouteImport.update({
  id: '/sms-log',
  path: '/sms-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseRequestsRoute = AdminPurchaseRequestsRouteImport.update({
  id: '/purchase-requests',
  path: '/purchase-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrepaidTicketsRoute = AdminPrepaidTicketsRouteImport.update({
  id: '/prepaid-tickets',
  path: '/prepaid-tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesIndexRoute = AdminVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesIdRoute = AdminVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesWorkOrderIdRoute =
  AdminInvoicesWorkOrderIdRouteImport.update({
    id: '/invoices/$workOrderId',
    path: '/invoices/$workOrderId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/prepaid-tickets': typeof AdminPrepaidTicketsRoute
  '/admin/purchase-requests': typeof AdminPurchaseRequestsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms-log': typeof AdminSmsLogRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/debug/error-boundary-trigger': typeof DebugErrorBoundaryTriggerRoute
  '/driver/end-of-day': typeof DriverEndOfDayRoute
  '/driver/forms': typeof DriverFormsRoute
  '/driver/inspection': typeof DriverInspectionRoute
  '/driver/job-log': typeof DriverJobLogRoute
  '/driver/jobs': typeof DriverJobsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/start-of-day': typeof DriverStartOfDayRoute
  '/driver/tickets': typeof DriverTicketsRoute
  '/driver/tool-checklist': typeof DriverToolChecklistRoute
  '/driver/work-order': typeof DriverWorkOrderRoute
  '/mechanic/inventory': typeof MechanicInventoryRoute
  '/mechanic/maintenance': typeof MechanicMaintenanceRoute
  '/mechanic/purchase-requests': typeof MechanicPurchaseRequestsRoute
  '/mechanic/work-orders': typeof MechanicWorkOrdersRoute
  '/t/$token': typeof TTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/admin/invoices/$workOrderId': typeof AdminInvoicesWorkOrderIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/prepaid-tickets': typeof AdminPrepaidTicketsRoute
  '/admin/purchase-requests': typeof AdminPurchaseRequestsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms-log': typeof AdminSmsLogRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/debug/error-boundary-trigger': typeof DebugErrorBoundaryTriggerRoute
  '/driver/end-of-day': typeof DriverEndOfDayRoute
  '/driver/forms': typeof DriverFormsRoute
  '/driver/inspection': typeof DriverInspectionRoute
  '/driver/job-log': typeof DriverJobLogRoute
  '/driver/jobs': typeof DriverJobsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/start-of-day': typeof DriverStartOfDayRoute
  '/driver/tickets': typeof DriverTicketsRoute
  '/driver/tool-checklist': typeof DriverToolChecklistRoute
  '/driver/work-order': typeof DriverWorkOrderRoute
  '/mechanic/inventory': typeof MechanicInventoryRoute
  '/mechanic/maintenance': typeof MechanicMaintenanceRoute
  '/mechanic/purchase-requests': typeof MechanicPurchaseRequestsRoute
  '/mechanic/work-orders': typeof MechanicWorkOrdersRoute
  '/t/$token': typeof TTokenRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/mechanic': typeof MechanicIndexRoute
  '/admin/invoices/$workOrderId': typeof AdminInvoicesWorkOrderIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/prepaid-tickets': typeof AdminPrepaidTicketsRoute
  '/admin/purchase-requests': typeof AdminPurchaseRequestsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms-log': typeof AdminSmsLogRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/work-orders': typeof AdminWorkOrdersRoute
  '/debug/error-boundary-trigger': typeof DebugErrorBoundaryTriggerRoute
  '/driver/end-of-day': typeof DriverEndOfDayRoute
  '/driver/forms': typeof DriverFormsRoute
  '/driver/inspection': typeof DriverInspectionRoute
  '/driver/job-log': typeof DriverJobLogRoute
  '/driver/jobs': typeof DriverJobsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/start-of-day': typeof DriverStartOfDayRoute
  '/driver/tickets': typeof DriverTicketsRoute
  '/driver/tool-checklist': typeof DriverToolChecklistRoute
  '/driver/work-order': typeof DriverWorkOrderRoute
  '/mechanic/inventory': typeof MechanicInventoryRoute
  '/mechanic/maintenance': typeof MechanicMaintenanceRoute
  '/mechanic/purchase-requests': typeof MechanicPurchaseRequestsRoute
  '/mechanic/work-orders': typeof MechanicWorkOrdersRoute
  '/t/$token': typeof TTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/admin/invoices/$workOrderId': typeof AdminInvoicesWorkOrderIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/mechanic'
    | '/admin/clients'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/forms'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/prepaid-tickets'
    | '/admin/purchase-requests'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sms-log'
    | '/admin/tenders'
    | '/admin/tickets'
    | '/admin/timesheets'
    | '/admin/work-orders'
    | '/debug/error-boundary-trigger'
    | '/driver/end-of-day'
    | '/driver/forms'
    | '/driver/inspection'
    | '/driver/job-log'
    | '/driver/jobs'
    | '/driver/profile'
    | '/driver/start-of-day'
    | '/driver/tickets'
    | '/driver/tool-checklist'
    | '/driver/work-order'
    | '/mechanic/inventory'
    | '/mechanic/maintenance'
    | '/mechanic/purchase-requests'
    | '/mechanic/work-orders'
    | '/t/$token'
    | '/admin/'
    | '/driver/'
    | '/mechanic/'
    | '/admin/invoices/$workOrderId'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/clients'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/forms'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/prepaid-tickets'
    | '/admin/purchase-requests'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sms-log'
    | '/admin/tenders'
    | '/admin/tickets'
    | '/admin/timesheets'
    | '/admin/work-orders'
    | '/debug/error-boundary-trigger'
    | '/driver/end-of-day'
    | '/driver/forms'
    | '/driver/inspection'
    | '/driver/job-log'
    | '/driver/jobs'
    | '/driver/profile'
    | '/driver/start-of-day'
    | '/driver/tickets'
    | '/driver/tool-checklist'
    | '/driver/work-order'
    | '/mechanic/inventory'
    | '/mechanic/maintenance'
    | '/mechanic/purchase-requests'
    | '/mechanic/work-orders'
    | '/t/$token'
    | '/admin'
    | '/driver'
    | '/mechanic'
    | '/admin/invoices/$workOrderId'
    | '/admin/vehicles/$id'
    | '/admin/vehicles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/mechanic'
    | '/admin/clients'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/forms'
    | '/admin/jobs'
    | '/admin/map'
    | '/admin/prepaid-tickets'
    | '/admin/purchase-requests'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sms-log'
    | '/admin/tenders'
    | '/admin/tickets'
    | '/admin/timesheets'
    | '/admin/work-orders'
    | '/debug/error-boundary-trigger'
    | '/driver/end-of-day'
    | '/driver/forms'
    | '/driver/inspection'
    | '/driver/job-log'
    | '/driver/jobs'
    | '/driver/profile'
    | '/driver/start-of-day'
    | '/driver/tickets'
    | '/driver/tool-checklist'
    | '/driver/work-order'
    | '/mechanic/inventory'
    | '/mechanic/maintenance'
    | '/mechanic/purchase-requests'
    | '/mechanic/work-orders'
    | '/t/$token'
    | '/admin/'
    | '/driver/'
    | '/mechanic/'
    | '/admin/invoices/$workOrderId'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  MechanicRoute: typeof MechanicRouteWithChildren
  DebugErrorBoundaryTriggerRoute: typeof DebugErrorBoundaryTriggerRoute
  TTokenRoute: typeof TTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mechanic': {
      id: '/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof MechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic/': {
      id: '/mechanic/'
      path: '/'
      fullPath: '/mechanic/'
      preLoaderRoute: typeof MechanicIndexRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic/work-orders': {
      id: '/mechanic/work-orders'
      path: '/work-orders'
      fullPath: '/mechanic/work-orders'
      preLoaderRoute: typeof MechanicWorkOrdersRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/purchase-requests': {
      id: '/mechanic/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/mechanic/purchase-requests'
      preLoaderRoute: typeof MechanicPurchaseRequestsRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/maintenance': {
      id: '/mechanic/maintenance'
      path: '/maintenance'
      fullPath: '/mechanic/maintenance'
      preLoaderRoute: typeof MechanicMaintenanceRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/inventory': {
      id: '/mechanic/inventory'
      path: '/inventory'
      fullPath: '/mechanic/inventory'
      preLoaderRoute: typeof MechanicInventoryRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/driver/work-order': {
      id: '/driver/work-order'
      path: '/work-order'
      fullPath: '/driver/work-order'
      preLoaderRoute: typeof DriverWorkOrderRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/tool-checklist': {
      id: '/driver/tool-checklist'
      path: '/tool-checklist'
      fullPath: '/driver/tool-checklist'
      preLoaderRoute: typeof DriverToolChecklistRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/tickets': {
      id: '/driver/tickets'
      path: '/tickets'
      fullPath: '/driver/tickets'
      preLoaderRoute: typeof DriverTicketsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/start-of-day': {
      id: '/driver/start-of-day'
      path: '/start-of-day'
      fullPath: '/driver/start-of-day'
      preLoaderRoute: typeof DriverStartOfDayRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/jobs': {
      id: '/driver/jobs'
      path: '/jobs'
      fullPath: '/driver/jobs'
      preLoaderRoute: typeof DriverJobsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/job-log': {
      id: '/driver/job-log'
      path: '/job-log'
      fullPath: '/driver/job-log'
      preLoaderRoute: typeof DriverJobLogRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/inspection': {
      id: '/driver/inspection'
      path: '/inspection'
      fullPath: '/driver/inspection'
      preLoaderRoute: typeof DriverInspectionRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/forms': {
      id: '/driver/forms'
      path: '/forms'
      fullPath: '/driver/forms'
      preLoaderRoute: typeof DriverFormsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/end-of-day': {
      id: '/driver/end-of-day'
      path: '/end-of-day'
      fullPath: '/driver/end-of-day'
      preLoaderRoute: typeof DriverEndOfDayRouteImport
      parentRoute: typeof DriverRoute
    }
    '/debug/error-boundary-trigger': {
      id: '/debug/error-boundary-trigger'
      path: '/debug/error-boundary-trigger'
      fullPath: '/debug/error-boundary-trigger'
      preLoaderRoute: typeof DebugErrorBoundaryTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/work-orders': {
      id: '/admin/work-orders'
      path: '/work-orders'
      fullPath: '/admin/work-orders'
      preLoaderRoute: typeof AdminWorkOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenders': {
      id: '/admin/tenders'
      path: '/tenders'
      fullPath: '/admin/tenders'
      preLoaderRoute: typeof AdminTendersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms-log': {
      id: '/admin/sms-log'
      path: '/sms-log'
      fullPath: '/admin/sms-log'
      preLoaderRoute: typeof AdminSmsLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-requests': {
      id: '/admin/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/admin/purchase-requests'
      preLoaderRoute: typeof AdminPurchaseRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prepaid-tickets': {
      id: '/admin/prepaid-tickets'
      path: '/prepaid-tickets'
      fullPath: '/admin/prepaid-tickets'
      preLoaderRoute: typeof AdminPrepaidTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles/': {
      id: '/admin/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AdminVehiclesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles/$id': {
      id: '/admin/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/admin/vehicles/$id'
      preLoaderRoute: typeof AdminVehiclesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$workOrderId': {
      id: '/admin/invoices/$workOrderId'
      path: '/invoices/$workOrderId'
      fullPath: '/admin/invoices/$workOrderId'
      preLoaderRoute: typeof AdminInvoicesWorkOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminPrepaidTicketsRoute: typeof AdminPrepaidTicketsRoute
  AdminPurchaseRequestsRoute: typeof AdminPurchaseRequestsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsLogRoute: typeof AdminSmsLogRoute
  AdminTendersRoute: typeof AdminTendersRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminWorkOrdersRoute: typeof AdminWorkOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInvoicesWorkOrderIdRoute: typeof AdminInvoicesWorkOrderIdRoute
  AdminVehiclesIdRoute: typeof AdminVehiclesIdRoute
  AdminVehiclesIndexRoute: typeof AdminVehiclesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminPrepaidTicketsRoute: AdminPrepaidTicketsRoute,
  AdminPurchaseRequestsRoute: AdminPurchaseRequestsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsLogRoute: AdminSmsLogRoute,
  AdminTendersRoute: AdminTendersRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminWorkOrdersRoute: AdminWorkOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInvoicesWorkOrderIdRoute: AdminInvoicesWorkOrderIdRoute,
  AdminVehiclesIdRoute: AdminVehiclesIdRoute,
  AdminVehiclesIndexRoute: AdminVehiclesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverEndOfDayRoute: typeof DriverEndOfDayRoute
  DriverFormsRoute: typeof DriverFormsRoute
  DriverInspectionRoute: typeof DriverInspectionRoute
  DriverJobLogRoute: typeof DriverJobLogRoute
  DriverJobsRoute: typeof DriverJobsRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverStartOfDayRoute: typeof DriverStartOfDayRoute
  DriverTicketsRoute: typeof DriverTicketsRoute
  DriverToolChecklistRoute: typeof DriverToolChecklistRoute
  DriverWorkOrderRoute: typeof DriverWorkOrderRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEndOfDayRoute: DriverEndOfDayRoute,
  DriverFormsRoute: DriverFormsRoute,
  DriverInspectionRoute: DriverInspectionRoute,
  DriverJobLogRoute: DriverJobLogRoute,
  DriverJobsRoute: DriverJobsRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverStartOfDayRoute: DriverStartOfDayRoute,
  DriverTicketsRoute: DriverTicketsRoute,
  DriverToolChecklistRoute: DriverToolChecklistRoute,
  DriverWorkOrderRoute: DriverWorkOrderRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface MechanicRouteChildren {
  MechanicInventoryRoute: typeof MechanicInventoryRoute
  MechanicMaintenanceRoute: typeof MechanicMaintenanceRoute
  MechanicPurchaseRequestsRoute: typeof MechanicPurchaseRequestsRoute
  MechanicWorkOrdersRoute: typeof MechanicWorkOrdersRoute
  MechanicIndexRoute: typeof MechanicIndexRoute
}

const MechanicRouteChildren: MechanicRouteChildren = {
  MechanicInventoryRoute: MechanicInventoryRoute,
  MechanicMaintenanceRoute: MechanicMaintenanceRoute,
  MechanicPurchaseRequestsRoute: MechanicPurchaseRequestsRoute,
  MechanicWorkOrdersRoute: MechanicWorkOrdersRoute,
  MechanicIndexRoute: MechanicIndexRoute,
}

const MechanicRouteWithChildren = MechanicRoute._addFileChildren(
  MechanicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  MechanicRoute: MechanicRouteWithChildren,
  DebugErrorBoundaryTriggerRoute: DebugErrorBoundaryTriggerRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
